on: [push]

jobs:
  e2e_test_job:
    runs-on: ubuntu-latest
    container:
      image: arjun27/playwright-bionic:0.1.0
    name: Try playwright
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: "echo $HOME"
    - run: "stat $HOME"
    - run: "id"
    - run: cd test-project && npm install && node index.js
